twig:
    file_name_pattern: '*.twig'
    globals:
        character_photo_dir: "/uploads/photos/characters"
        player_photo_dir: "/uploads/photos/players"

when@test:
    twig:
        strict_variables: true
